///generic dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_LARGE_2 = 28.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XLARGE_2 = 48.0;

const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

///app specific
const SEARCH_BAR_BORDER_RADIUS = 8.0;
const SEARCH_BAR_PROFILE_IMAGE_SIZE = 24.0;
const REVIEW_PROFILE_IMAGE_SIZE = 32.0;
const CAROUSEL_ITEM_BORDER_RADIUS = 12.0;
const CAROUSEL_ITEM_BUTTON_BORDER_RADIUS = 8.0;
const BOOK_COVER_IMAGE_RADIUS = 8.0;
const CAROUSEL_OPTION_IMAGE_RADIUS = 8.0;
const SEARCH_RESULT_IMAGE_HEIGHT = 52.0;
const SEARCH_RESULT_IMAGE_WIDTH = 32.0;
const IMAGE_RADIUS = 8.0;
const SEE_MORE_BUTTON_SIZE = 16.0;
const HORIZONTAL_BOOK_LIST_HEIGHT = 204.0;
const HORIZONTAL_SIMILAR_BOOK_LIST_HEIGHT = 250.0;
const THREE_COLUMN_BOOK_IMAGE_HEIGHT = 160.0;
const BOOK_IMAGE_HEIGHT = 160.0;
const SIMILAR_BOOK_IMAGE_HEIGHT = 190.0;
const TWO_COLUMN_BOOK_IMAGE_HEIGHT = 240.0;
const BOOK_IMAGE_WIDTH = 120.0;
const SIMILAR_BOOK_IMAGE_WIDTH = 150.0;
const LIST_VIEW_ITEM_HEIGHT = 80.0;
const SHELF_VIEW_ITEM_HEIGHT = 72.0;
const FILTER_LIST_VIEW_HEIGHT = 40.0;
const BOOK_DETAIL_IMAGE_HEIGHT = 160.0;
const BOOK_DETAIL_IMAGE_WIDTH = 92.0;
